version: "3.9"
services:
  ros_docker:
    extends:
      file: docker-compose-gui.yml
      service: ros_docker
    cap_add:
      # Required for GDB debugging with ROS extension
      - SYS_PTRACE
    volumes:
      - ../.vscode:${CATKIN_WORKSPACE_DIR}/.vscode

