version: "3.9"
services:
  ros_docker:
    extends:
      file: docker-compose-gui.yml
      service: ros_docker
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
