version: "3.9"
services:
  ros_docker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - CATKIN_WORKSPACE_DIR=${CATKIN_WORKSPACE_DIR}
        - USERNAME=${USERNAME:-developer}
        - UID=${UID:-1000}
        - GID=${UID:-1000}
    container_name: ros_docker
    environment:
      - ROS_MASTER_URI=http://${ROBOT_IP}:11311
      - ROS_IP=${YOUR_IP}
    extra_hosts:
      - "${ROBOT_HOSTNAME}:${ROBOT_IP}"
    image: ros_template:devel
    network_mode: "host"
    tty: true
    volumes:
      - ../src:${CATKIN_WORKSPACE_DIR}/src

